name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      # Cleans old builds first, then generates the bundle
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean :patches:buildAndroid generatePatchesList

      # Automatically creates a public GitHub Release and uploads the .mpp file
      # Change the tag and name lines below whenever you want to bump the version number!
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/build/libs/patches-*.mpp,patches-bundle.json,patches-list.json"
          tag: "v1.8.2"
          name: "Release v1.8.2"
          body: "Automated build of Morphe Patches Bundle."
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge jsDelivr Cache
        run: |
          for file in patches-bundle.json patches-list.json; do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref_name }}/$file"
          done
